### ISSUE TITLE
Option names can not include `-` in them

### ISSUE THREAD

**Issue by majormoses** [chef/mixlib-cli#48]
# Version:

`mixlib-cli-1.7.0`

# Environment: [Details about the environment such as the Operating System, cookbook details, etc...]

Unsure see: https://github.com/sensu-plugins/sensu-plugins-disk-checks/issues/94

# Scenario:

[What you are trying to achieve and you can't?]

Use an arg such as `--no-smart-capable-disks`

# Steps to Reproduce:

1. clone repo: https://github.com/sensu-plugins/sensu-plugins-disk-checks
1. run `bundle`
1. run script:
```
$ bundle exec ./bin/check-smart.rb --no-smart-capable-disks
Check failed to run: undefined method `to_sym' for false:FalseClass
Did you mean?  to_s, ["/home/babrams/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/mixlib-cli-1.7.0/lib/mixlib/cli.rb:290:in `block (3 levels) in opt_parser'", "/home/babrams/.rbenv/versions/2.4.1/lib/ruby/2.4.0/optparse.rb:1552:in `block in parse_in_order'", "/home/babrams/.rbenv/versions/2.4.1/lib/ruby/2.4.0/optparse.rb:1538:in `catch'", "/home/babrams/.rbenv/versions/2.4.1/lib/ruby/2.4.0/optparse.rb:1538:in `parse_in_order'", "/home/babrams/.rbenv/versions/2.4.1/lib/ruby/2.4.0/optparse.rb:1532:in `order!'", "/home/babrams/.rbenv/versions/2.4.1/lib/ruby/2.4.0/optparse.rb:1626:in `permute!'", "/home/babrams/.rbenv/versions/2.4.1/lib/ruby/2.4.0/optparse.rb:1648:in `parse!'", "/home/babrams/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/mixlib-cli-1.7.0/lib/mixlib/cli.rb:230:in `parse_options'", "/home/babrams/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sensu-plugin-1.4.5/lib/sensu-plugin/cli.rb:13:in `initialize'", "./bin/check-smart.rb:138:in `initialize'", "/home/babrams/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sensu-plugin-1.4.5/lib/sensu-plugin/cli.rb:57:in `new'", "/home/babrams/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sensu-plugin-1.4.5/lib/sensu-plugin/cli.rb:57:in `block in <class:CLI>'"]
```
[If you are filing an issue what are the things we need to do in order to repro your problem?]

# Expected Result:

Argument should work

[What are you expecting to happen as the consequence of above reproduction steps?]

# Actual Result:

It blows up and does not parse the arguments properly

[What actually happens after the reproduction steps?]

**Comment by majormoses** [comment]
After doing a bit more digging [here](https://github.com/sensu-plugins/sensu-plugins-disk-checks/pull/95#issuecomment-415966550) it would appear that the issue happens when the long option starts with `--no-*` which is something I am guessing is auto generated to negate an option. I am not sure how to solve this but maybe we can put some validation in during the auto generation of the negation option and if there is a conflict we can minimally log something.
